language: php

sudo: false

php:
    - 7.4

before_install:
    - composer self-update

install:
    - composer install --prefer-source

script:
    - php app/vendor/bin/phpunit

matrix:
    allow_failures:
        - php: 7.4
    fast_finish: true
